version: "3.8"
services:
  database:
    image: mysql:5.7
    environment:
            MYSQL_ROOT_PASSWORD: 123456789
            MYSQL_DATABASE: db
            MYSQL_USER: rkn
            MYSQL_PASSWORD: rkn1234
    volumes:
      - db-data:/var/lib/mysql
    configs:
      - source: rknTable
        target: /docker-entrypoint-initdb.d/init.sql
    networks:
      - rknnet

  appserver:
    env_file: .env
    image: "${ECR_REPO}:latest"
    deploy: 
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first

    ports:
      - "80:80"
    networks:
      - rknnet


networks:
  rknnet:
volumes:
  db-data:
config:
  rknTable:
    file: ./init.sql

